name: JMeter Performance Test
on: [push]
jobs:
  performance_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JMeter
        run: |
          sudo apt-get update
          sudo apt install jmeter -y

      - name: Run JMeter Test
        # We use *.jmx so it finds the file even if the name is slightly off
        run: |
          ls -F
          jmeter -n -t *.jmx -l results.jtl

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: results.jtl
