name: JMeter Performance Test
on: [push]
jobs:
  performance_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JMeter
        run: |
          sudo apt-get update
          sudo apt install jmeter -y

      - name: Run JMeter Test
        # We use -f to force JMeter to ignore some non-critical errors 
        # and ensure the .jtl is created
        run: |
          jmeter -n -t "*.jmx" -l results.jtl -j jmeter.log
          ls -lh

      - name: Upload Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: |
            results.jtl
            jmeter.log
